const weatheralertcolorcodes = {
  "Hazard-WeatherEvent": {
    "Tsunami Warning": {
      Priority: "1",
      ColorName: "Tomato",
      RGBColor: "253 99 71",
      HexCode: "FD6347",
    },
    "Tornado Warning": {
      Priority: "2",
      ColorName: "Red",
      RGBColor: "255 0 0",
      HexCode: "FF0000",
    },
    "Extreme Wind Warning": {
      Priority: "3",
      ColorName: "Darkorange",
      RGBColor: "255 140 0",
      HexCode: "FF8C00",
    },
    "Severe Thunderstorm Warning": {
      Priority: "4",
      ColorName: "Orange",
      RGBColor: "255 165 0",
      HexCode: "FFA500",
    },
    "Flash Flood Warning": {
      Priority: "5",
      ColorName: "Darkred",
      RGBColor: "139 0 0",
      HexCode: "8B0000",
    },
    "Flash Flood Statement": {
      Priority: "6",
      ColorName: "Darkred",
      RGBColor: "139 0 0",
      HexCode: "8B0000",
    },
    "Severe Weather Statement": {
      Priority: "7",
      ColorName: "Aqua",
      RGBColor: "0 255 255",
      HexCode: "00FFFF",
    },
    "Shelter In Place Warning": {
      Priority: "8",
      ColorName: "Salmon",
      RGBColor: "250 128 114",
      HexCode: "FA8072",
    },
    "Evacuation Immediate": {
      Priority: "9",
      ColorName: "Chartreuse",
      RGBColor: "127 255 0",
      HexCode: "7FFF00",
    },
    "Civil Danger Warning": {
      Priority: "10",
      ColorName: "Lightpink",
      RGBColor: "255 182 193",
      HexCode: "FFB6C1",
    },
    "Nuclear Power Plant Warning": {
      Priority: "11",
      ColorName: "Indigo",
      RGBColor: "75 0 130",
      HexCode: "4B0082",
    },
    "Radiological Hazard Warning": {
      Priority: "12",
      ColorName: "Indigo",
      RGBColor: "75 0 130",
      HexCode: "4B0082",
    },
    "Hazardous Materials Warning": {
      Priority: "13",
      ColorName: "Indigo",
      RGBColor: "75 0 130",
      HexCode: "4B0082",
    },
    "Fire Warning": {
      Priority: "14",
      ColorName: "Sienna",
      RGBColor: "160 82 45",
      HexCode: "A0522D",
    },
    "Civil Emergency Message": {
      Priority: "15",
      ColorName: "Lightpink",
      RGBColor: "255 182 193",
      HexCode: "FFB6C1",
    },
    "Law Enforcement Warning": {
      Priority: "16",
      ColorName: "Silver",
      RGBColor: "192 192 192",
      HexCode: "C0C0C0",
    },
    "Storm Surge Warning": {
      Priority: "17",
      ColorName: "Darkpurple",
      RGBColor: "181 36 247",
      HexCode: "B524F7",
    },
    "Hurricane Force Wind Warning": {
      Priority: "18",
      ColorName: "Westernred",
      RGBColor: "205 92 92",
      HexCode: "CD5C5C",
    },
    "Hurricane Warning": {
      Priority: "19",
      ColorName: "Crimson",
      RGBColor: "220 20 60",
      HexCode: "DC143C",
    },
    "Typhoon Warning": {
      Priority: "20",
      ColorName: "Crimson",
      RGBColor: "220 20 60",
      HexCode: "DC143C",
    },
    "Special Marine Warning": {
      Priority: "21",
      ColorName: "Orange",
      RGBColor: "255 165 0",
      HexCode: "FFA500",
    },
    "Blizzard Warning": {
      Priority: "22",
      ColorName: "Orangered",
      RGBColor: "255 69 0",
      HexCode: "FF4500",
    },
    "Snow Squall Warning": {
      Priority: "23",
      ColorName: "Mediumvioletred",
      RGBColor: "199 21 133",
      HexCode: "C71585",
    },
    "Ice Storm Warning": {
      Priority: "24",
      ColorName: "Darkmagenta",
      RGBColor: "139 0 139",
      HexCode: "8B008B",
    },
    "Winter Storm Warning": {
      Priority: "25",
      ColorName: "Hotpink",
      RGBColor: "255 105 180",
      HexCode: "FF69B4",
    },
    "High Wind Warning": {
      Priority: "26",
      ColorName: "Goldenrod",
      RGBColor: "218 165 32",
      HexCode: "DAA520",
    },
    "Tropical Storm Warning": {
      Priority: "27",
      ColorName: "Firebrick",
      RGBColor: "178 34 34",
      HexCode: "B22222",
    },
    "Storm Warning": {
      Priority: "28",
      ColorName: "Darkviolet",
      RGBColor: "148 0 211",
      HexCode: "9400D3",
    },
    "Tsunami Advisory": {
      Priority: "29",
      ColorName: "Chocolate",
      RGBColor: "210 105 30",
      HexCode: "D2691E",
    },
    "Tsunami Watch": {
      Priority: "30",
      ColorName: "Fushsia",
      RGBColor: "255 0 255",
      HexCode: "FF00FF",
    },
    "Avalanche Warning": {
      Priority: "31",
      ColorName: "Dodgerblue",
      RGBColor: "30 144 255",
      HexCode: "1E90FF",
    },
    "Earthquake Warning": {
      Priority: "32",
      ColorName: "Saddlebrown",
      RGBColor: "139 69 19",
      HexCode: "8B4513",
    },
    "Volcano Warning": {
      Priority: "33",
      ColorName: "darkslategray",
      RGBColor: "47 79 79",
      HexCode: "2F4F4F",
    },
    "Ashfall Warning": {
      Priority: "34",
      ColorName: "Darkgray",
      RGBColor: "169 169 169",
      HexCode: "A9A9A9",
    },
    "Coastal Flood Warning": {
      Priority: "35",
      ColorName: "Forestgreen",
      RGBColor: "34 139 34",
      HexCode: "228B22",
    },
    "Lakeshore Flood Warning": {
      Priority: "36",
      ColorName: "Forestgreen",
      RGBColor: "34 139 34",
      HexCode: "228B22",
    },
    "Flood Warning": {
      Priority: "37",
      ColorName: "Lime",
      RGBColor: "0 255 0",
      HexCode: "00FF00",
    },
    "High Surf Warning": {
      Priority: "38",
      ColorName: "Forestgreen",
      RGBColor: "34 139 34",
      HexCode: "228B22",
    },
    "Dust Storm Warning": {
      Priority: "39",
      ColorName: "Bisque",
      RGBColor: "255 228 196",
      HexCode: "FFE4C4",
    },
    "Blowing Dust Warning": {
      Priority: "40",
      ColorName: "Bisque",
      RGBColor: "255 228 196",
      HexCode: "FFE4C4",
    },
    "Lake Effect Snow Warning": {
      Priority: "41",
      ColorName: "Darkcyan",
      RGBColor: "0 139 139",
      HexCode: "008B8B",
    },
    "Excessive Heat Warning": {
      Priority: "42",
      ColorName: "Mediumvioletred",
      RGBColor: "199 21 133",
      HexCode: "C71585",
    },
    "Tornado Watch": {
      Priority: "43",
      ColorName: "Yellow",
      RGBColor: "255 255 0",
      HexCode: "FFFF00",
    },
    "Severe Thunderstorm Watch": {
      Priority: "44",
      ColorName: "Palevioletred",
      RGBColor: "219 112 147",
      HexCode: "DB7093",
    },
    "Flash Flood Watch": {
      Priority: "45",
      ColorName: "Seagreen",
      RGBColor: "46 139 87",
      HexCode: "2E8B57",
    },
    "Gale Warning": {
      Priority: "46",
      ColorName: "Plum",
      RGBColor: "221 160 221",
      HexCode: "DDA0DD",
    },
    "Flood Statement": {
      Priority: "47",
      ColorName: "Lime",
      RGBColor: "0 255 0",
      HexCode: "00FF00",
    },
    "Wind Chill Warning": {
      Priority: "48",
      ColorName: "Lightsteelblue",
      RGBColor: "176 196 222",
      HexCode: "B0C4DE",
    },
    "Extreme Cold Warning": {
      Priority: "49",
      ColorName: "Blue",
      RGBColor: "0 0 255",
      HexCode: "0000FF",
    },
    "Hard Freeze Warning": {
      Priority: "50",
      ColorName: "Darkviolet",
      RGBColor: "148 0 211",
      HexCode: "9400D3",
    },
    "Freeze Warning": {
      Priority: "51",
      ColorName: "Darkslateblue",
      RGBColor: "72 61 139",
      HexCode: "483D8B",
    },
    "Red Flag Warning": {
      Priority: "52",
      ColorName: "Deeppink",
      RGBColor: "255 20 147",
      HexCode: "FF1493",
    },
    "Storm Surge Watch": {
      Priority: "53",
      ColorName: "Lightpurple",
      RGBColor: "219 127 247",
      HexCode: "DB7FF7",
    },
    "Hurricane Watch": {
      Priority: "54",
      ColorName: "Magenta",
      RGBColor: "255 0 255",
      HexCode: "FF00FF",
    },
    "Hurricane Force Wind Watch": {
      Priority: "55",
      ColorName: "Darkorchid",
      RGBColor: "153 50 204",
      HexCode: "9932CC",
    },
    "Typhoon Watch": {
      Priority: "56",
      ColorName: "Magenta",
      RGBColor: "255 0 255",
      HexCode: "FF00FF",
    },
    "Tropical Storm Watch": {
      Priority: "57",
      ColorName: "Lightcoral",
      RGBColor: "240 128 128",
      HexCode: "F08080",
    },
    "Storm Watch": {
      Priority: "58",
      ColorName: "Moccasin",
      RGBColor: "255 228 181",
      HexCode: "FFE4B5",
    },
    "Hurricane Local Statement": {
      Priority: "59",
      ColorName: "Moccasin",
      RGBColor: "255 228 181",
      HexCode: "FFE4B5",
    },
    "Typhoon Local Statement": {
      Priority: "60",
      ColorName: "Moccasin",
      RGBColor: "255 228 181",
      HexCode: "FFE4B5",
    },
    "Tropical Storm Local Statement": {
      Priority: "61",
      ColorName: "Moccasin",
      RGBColor: "255 228 181",
      HexCode: "FFE4B5",
    },
    "Tropical Depression Local Statement": {
      Priority: "62",
      ColorName: "Moccasin",
      RGBColor: "255 228 181",
      HexCode: "FFE4B5",
    },
    "Avalanche Advisory": {
      Priority: "63",
      ColorName: "Peru",
      RGBColor: "205 133 63",
      HexCode: "CD853F",
    },
    "Winter Weather Advisory": {
      Priority: "64",
      ColorName: "Mediumslateblue",
      RGBColor: "123 104 238",
      HexCode: "7B68EE",
    },
    "Wind Chill Advisory": {
      Priority: "65",
      ColorName: "Paleturquoise",
      RGBColor: "175 238 238",
      HexCode: "AFEEEE",
    },
    "Heat Advisory": {
      Priority: "66",
      ColorName: "Coral",
      RGBColor: "255 127 80",
      HexCode: "FF7F50",
    },
    "Urban and Small Stream Flood Advisory": {
      Priority: "67",
      ColorName: "Springgreen",
      RGBColor: "0 255 127",
      HexCode: "00FF7F",
    },
    "Small Stream Flood Advisory": {
      Priority: "68",
      ColorName: "Springgreen",
      RGBColor: "0 255 127",
      HexCode: "00FF7F",
    },
    "Arroyo and Small Stream Flood Advisory": {
      Priority: "69",
      ColorName: "Springgreen",
      RGBColor: "0 255 127",
      HexCode: "00FF7F",
    },
    "Flood Advisory": {
      Priority: "70",
      ColorName: "Springgreen",
      RGBColor: "0 255 127",
      HexCode: "00FF7F",
    },
    "Hydrologic Advisory": {
      Priority: "71",
      ColorName: "Springgreen",
      RGBColor: "0 255 127",
      HexCode: "00FF7F",
    },
    "Lakeshore Flood Advisory": {
      Priority: "72",
      ColorName: "Lawngreen",
      RGBColor: "124 252 0",
      HexCode: "7CFC00",
    },
    "Coastal Flood Advisory": {
      Priority: "73",
      ColorName: "Lawngreen",
      RGBColor: "124 252 0",
      HexCode: "7CFC00",
    },
    "High Surf Advisory": {
      Priority: "74",
      ColorName: "Mediumorchid",
      RGBColor: "186 85 211",
      HexCode: "BA55D3",
    },
    "Heavy Freezing Spray Warning": {
      Priority: "75",
      ColorName: "Deepskyblue",
      RGBColor: "0 191 255",
      HexCode: "00BFFF",
    },
    "Dense Fog Advisory": {
      Priority: "76",
      ColorName: "Slategray",
      RGBColor: "112 128 144",
      HexCode: "708090",
    },
    "Dense Smoke Advisory": {
      Priority: "77",
      ColorName: "Khaki",
      RGBColor: "240 230 140",
      HexCode: "F0E68C",
    },
    "Small Craft Advisory": {
      Priority: "78",
      ColorName: "Thistle",
      RGBColor: "216 191 216",
      HexCode: "D8BFD8",
    },
    "Brisk Wind Advisory": {
      Priority: "79",
      ColorName: "Thistle",
      RGBColor: "216 191 216",
      HexCode: "D8BFD8",
    },
    "Hazardous Seas Warning": {
      Priority: "80",
      ColorName: "Thistle",
      RGBColor: "216 191 216",
      HexCode: "D8BFD8",
    },
    "Dust Advisory": {
      Priority: "81",
      ColorName: "Darkkhaki",
      RGBColor: "189 183 107",
      HexCode: "BDB76B",
    },
    "Blowing Dust Advisory": {
      Priority: "82",
      ColorName: "Darkkhaki",
      RGBColor: "189 183 107",
      HexCode: "BDB76B",
    },
    "Lake Wind Advisory": {
      Priority: "83",
      ColorName: "Tan",
      RGBColor: "210 180 140",
      HexCode: "D2B48C",
    },
    "Wind Advisory": {
      Priority: "84",
      ColorName: "Tan",
      RGBColor: "210 180 140",
      HexCode: "D2B48C",
    },
    "Frost Advisory": {
      Priority: "85",
      ColorName: "Cornflowerblue",
      RGBColor: "100 149 237",
      HexCode: "6495ED",
    },
    "Ashfall Advisory": {
      Priority: "86",
      ColorName: "Dimgray",
      RGBColor: "105 105 105",
      HexCode: "696969",
    },
    "Freezing Fog Advisory": {
      Priority: "87",
      ColorName: "Teal",
      RGBColor: "0 128 128",
      HexCode: "008080",
    },
    "Freezing Spray Advisory": {
      Priority: "88",
      ColorName: "Deepskyblue",
      RGBColor: "0 191 255",
      HexCode: "00BFFF",
    },
    "Low Water Advisory": {
      Priority: "89",
      ColorName: "Brown",
      RGBColor: "165 42 42",
      HexCode: "A52A2A",
    },
    "Local Area Emergency": {
      Priority: "90",
      ColorName: "Silver",
      RGBColor: "192 192 192",
      HexCode: "C0C0C0",
    },
    "Avalanche Watch": {
      Priority: "91",
      ColorName: "Sandybrown",
      RGBColor: "244 164 96",
      HexCode: "F4A460",
    },
    "Blizzard Watch": {
      Priority: "92",
      ColorName: "Greenyellow",
      RGBColor: "173 255 47",
      HexCode: "ADFF2F",
    },
    "Rip Current Statement": {
      Priority: "93",
      ColorName: "Turquoise",
      RGBColor: "64 224 208",
      HexCode: "40E0D0",
    },
    "Beach Hazards Statement": {
      Priority: "94",
      ColorName: "Turquoise",
      RGBColor: "64 224 208",
      HexCode: "40E0D0",
    },
    "Gale Watch": {
      Priority: "95",
      ColorName: "Pink",
      RGBColor: "255 192 203",
      HexCode: "FFC0CB",
    },
    "Winter Storm Watch": {
      Priority: "96",
      ColorName: "Steelblue",
      RGBColor: "70 130 180",
      HexCode: "4682B4",
    },
    "Hazardous Seas Watch": {
      Priority: "97",
      ColorName: "Darkslateblue",
      RGBColor: "72 61 139",
      HexCode: "483D8B",
    },
    "Heavy Freezing Spray Watch": {
      Priority: "98",
      ColorName: "Rosybrown",
      RGBColor: "188 143 143",
      HexCode: "BC8F8F",
    },
    "Coastal Flood Watch": {
      Priority: "99",
      ColorName: "Mediumaquamarine",
      RGBColor: "102 205 170",
      HexCode: "66CDAA",
    },
    "Lakeshore Flood Watch": {
      Priority: "100",
      ColorName: "Mediumaquamarine",
      RGBColor: "102 205 170",
      HexCode: "66CDAA",
    },
    "Flood Watch": {
      Priority: "101",
      ColorName: "Seagreen",
      RGBColor: "46 139 87",
      HexCode: "2E8B57",
    },
    "High Wind Watch": {
      Priority: "102",
      ColorName: "Darkgoldenrod",
      RGBColor: "184 134 11",
      HexCode: "B8860B",
    },
    "Excessive Heat Watch": {
      Priority: "103",
      ColorName: "Maroon",
      RGBColor: "128 0 0",
      HexCode: "800000",
    },
    "Extreme Cold Watch": {
      Priority: "104",
      ColorName: "Blue",
      RGBColor: "0 0 255",
      HexCode: "0000FF",
    },
    "Wind Chill Watch": {
      Priority: "105",
      ColorName: "Cadetblue",
      RGBColor: "95 158 160",
      HexCode: "5F9EA0",
    },
    "Lake Effect Snow Watch": {
      Priority: "106",
      ColorName: "Lightskyblue",
      RGBColor: "135 206 250",
      HexCode: "87CEFA",
    },
    "Hard Freeze Watch": {
      Priority: "107",
      ColorName: "Royalblue",
      RGBColor: "65 105 225",
      HexCode: "4169E1",
    },
    "Freeze Watch": {
      Priority: "108",
      ColorName: "Cyan",
      RGBColor: "0 255 255",
      HexCode: "00FFFF",
    },
    "Fire Weather Watch": {
      Priority: "109",
      ColorName: "Navajowhite",
      RGBColor: "255 222 173",
      HexCode: "FFDEAD",
    },
    "Extreme Fire Danger": {
      Priority: "110",
      ColorName: "Darksalmon",
      RGBColor: "233 150 122",
      HexCode: "E9967A",
    },
    "911 Telephone Outage": {
      Priority: "111",
      ColorName: "Silver",
      RGBColor: "192 192 192",
      HexCode: "C0C0C0",
    },
    "Coastal Flood Statement": {
      Priority: "112",
      ColorName: "Olivedrab",
      RGBColor: "107 142 35",
      HexCode: "6B8E23",
    },
    "Lakeshore Flood Statement": {
      Priority: "113",
      ColorName: "Olivedrab",
      RGBColor: "107 142 35",
      HexCode: "6B8E23",
    },
    "Special Weather Statement": {
      Priority: "114",
      ColorName: "Moccasin",
      RGBColor: "255 228 181",
      HexCode: "FFE4B5",
    },
    "Marine Weather Statement": {
      Priority: "115",
      ColorName: "Peachpuff",
      RGBColor: "255 239 213",
      HexCode: "FFDAB9",
    },
    "Air Quality Alert": {
      Priority: "116",
      ColorName: "Gray",
      RGBColor: "128 128 128",
      HexCode: "808080",
    },
    "Air Stagnation Advisory": {
      Priority: "117",
      ColorName: "Gray",
      RGBColor: "128 128 128",
      HexCode: "808080",
    },
    "Hazardous Weather Outlook": {
      Priority: "118",
      ColorName: "Palegoldenrod",
      RGBColor: "238 232 170",
      HexCode: "EEE8AA",
    },
    "Hydrologic Outlook": {
      Priority: "119",
      ColorName: "Lightgreen",
      RGBColor: "144 238 144",
      HexCode: "90EE90",
    },
    "Short Term Forecast": {
      Priority: "120",
      ColorName: "Palegreen",
      RGBColor: "152 251 152",
      HexCode: "98FB98",
    },
    "Administrative Message": {
      Priority: "121",
      ColorName: "Silver",
      RGBColor: "192 192 192",
      HexCode: "C0C0C0",
    },
    Test: {
      Priority: "122",
      ColorName: "Azure",
      RGBColor: "240 255 255",
      HexCode: "F0FFFF",
    },
    "Child Abduction Emergency": {
      Priority: "123",
      ColorName: "Transperant",
      RGBColor: "255 255 255",
      HexCode: "FFFFFF",
    },
    "Blue Alert": {
      Priority: "124",
      ColorName: "Transperant",
      RGBColor: "255 255 255",
      HexCode: "FFFFFF",
    },
  },
};
